version: '3.8'

services:
  test-db:
    image: mysql:8.0
    container_name: test-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 5
